#!/bin/sh
## upcase_lowcase for upcase_lowcase in /home/rodrigue.rene/Cours/Semestre_3/SCRIPT_BASH/SHL_2016_shell
## 
## Made by Rodrigue RENE
## Login   <rodrigue.rene@epitech.net>
## 
## Started on  Tue Jan  3 15:49:24 2017 Rodrigue RENE
## Last update Tue Jan  3 19:49:46 2017 Gregoire Renard
##

if [ -z $1 ]
then
    echo -e "USAGE: $0 -l -u">&2
    echo -e "-l : lowcase">&2
    echo -e "-u : upcase">&2
    exit 1
fi

allparams=("$@")
length=${#allparams[@]}
cpt=0
let "length = length - 1"
while [ $cpt -le $length ]
do
    if [ "${allparams[$cpt]}" != "-l" ] && [ "${allparams[$cpt]}" != "-u" ]
    then
	echo -e "ERROR: ${allparams[$cpt]} unknown option">&2
	exit 1
    fi
    let "cpt = cpt + 1"
done

option=${allparams[$length]}

cpt=0
while read line
do
    file[$cpt]=$line
    let "cpt = cpt + 1"
done

length=${#file[@]}
cpt=0

let "length = length - 1"
if [ "$option" == "-l" ]
then
    while [ "$cpt" -le "$length" ]
    do
	echo -e ${file[$cpt]} | sed -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'
	let "cpt = cpt + 1"
    done
    
fi
if [ "$option" == "-u" ]
then
    while [ "$cpt" -le "$length" ]
    do
	echo -e ${file[$cpt]} | sed -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'
	let "cpt = cpt + 1"
    done	
fi
